      PROGRAM MAIN

      DOUBLE PRECISION T, MJD, MIN_MJD, MAX_MJD, DUT, DLOD, DOMEGA
      INTEGER NUM_TESTS, I,J

      NUM_TESTS = 100
      MIN_MJD = 45700D0
      MAX_MJD = 62502D0

      DO I=1,NUM_TESTS-1
        CALL RANDOM_NUMBER(T)
        MJD = (MAX_MJD-MIN_MJD)*T + MIN_MJD
*       Julian centuries since J2000
        T = (MJD - 51544.5D0) / 36525D0
        CALL RG_ZONT2(T, DUT, DLOD, DOMEGA )
        WRITE(*,'(E30.22,X,E25.17,X,E25.17,X,E25.17)') 
     .  MJD, DUT, DLOD, DOMEGA
      END DO

      END
