iers-2010: iers2010::hisp Namespace Reference
iers2010::hisp Namespace Reference
Functions
int toymd (const int *, int *)
bool leap (const int &)
double etutc (const double &)
int eval (const double &, const int &, const double *, const double *, const double *, double &)
int recurs (double *, const int &, const double *, const int &, const double *, double *)
int shells (double *, int *, const int &)
int spline (const int &, const double *, const double *, double *, double *)
int tdfrph (const int *, const int *, double &, double &)
int admint (const double *, const int **, const double *, const int &, const int *, double *, double *, double *, int &)
int mday (const int &iy, const int &m)
int juldat (const int *it)
Function Documentation
int iers2010::hisp::admint (const double * ampin, const int ** idtin, const double * phin, const int & nin, const int * itm, double * amp, double * f, double * p, int & nout)
This function returns the ocean loading displacement amplitude, frequency, and phase of a set of tidal constituents generated by the Bos-Scherneck website at http://www.oso.chalmers.se/~loading/. The variable nin is input as the number wanted, and the variable nout is returned as the number provided. The constituents used are stored in the arrays idd (Doodson number) and tamp (Cartwright-Edden amplitude). The actual amp and phase of each of these are determined by spline interpolation of the real and imaginary part of the admittance, as specified at a subset of the constituents.
Parameters
[in] ampin Cartwright-Edden amplitude of tidal constituents (size nin).
[in] idtin Doodson number of tidal constituents (size 6xnin).
[in] phin Phase of tidal constituents
[in] nin Number of harmonics used
[in] itm Date as integer array in UTC. The format should be: [year,day_of_year,hours,minutes,seconds].
[out] amp Amplitude due to ocean loading
[out] f Frequency due to ocean loading
[out] p Phase due to ocean loading
[out] nout Number of harmonics returned
Returns
zero
Note
The phase is determined for a time set in COMMON block /date/ in the function TDFRPH.
The arrays F and P must be specified as double precision.
Status: Class 1 model
Version
2009 August 19
[McCarthy], D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Definition at line 40 of file admint.cpp.
References eval(), shells(), spline(), and tdfrph().
double iers2010::hisp::etutc (const double & year)
The purpose of the function is to compute the difference, delta, between Epheremis Time (ET) and Coordinated Universal Time (UTC).
Parameters
[in] year Decimal year (Note 1)
Returns
Delta ET - UTC (Note 2)
Note
This function is valid only from 1700.-until next leap second. Currently, this is up to 2012.5.
The expression used in given in seconds.
Leap second table in GAMIT UTC (and UT) is the time most often used (e.g. in time signals)
Status: Canonical model
Warning
IMPORTANT
A new version of this routine must be produced whenever a new leap second is announced. There are three items to change on each such occasion:
1) Update the nstep variable
2) Update the arrays st and si
3) Change date of latest leap second
Latest leap second: 2012 June 30
Todo:
Check the case 'For 1820.5 to 1961.5, data is spaced at yearly intervals'. There seems to be a mixup of integers and doubles ...
* Test case:
*     given input: year = 2007.0
*
*     expected output: delta = 65.1840000000000 seconds
*
*     given input: year = 2013.0
*
*     expected output: delta = 67.1840000000000 seconds
*
Version
2012 March 13
Definition at line 45 of file etutc.cpp.
int iers2010::hisp::eval (const double & y, const int & nn, const double * x, const double * s, const double * u, double & val)
This function performs cubic spline interpolation of a given function sampled at unequally spaced intervals. The subroutine SPLINE needs to be called beforehand to set up the array s.
Parameters
[in] y The coordinate at which a function value is desired (Note 1)
[in] nn Number of samples of the original function
[in] x Array containing sample coordinates x(1),x(2),...x(nn) (Note 2)
[in] s Array containing the 2nd derivatives at the sample points (Note 3)
[in] u Array containing samples of a function at the coordinates x(1),x(2),...x(nn)
[out] val The interpolated value of the function at y
Returns
Zero on success; else 1.
Note
If y falls outside the range (x(1),x(nn)), the value at the nearest endpoint of the series is used.
The sequence x(1),x(2),...x(nn) must be strictly increasing.
This array is found by the function SPLINE, which must be called once before beginning this interpolation.
Version
2009 August 19
Definition at line 27 of file eval.cpp.
int iers2010::hisp::juldat (const int * it) inline
This function converts a Gregorian date to a Julian date.
Parameters
[in] it A Gregorian date (Note 1)
Returns
The corresponding Julian date (Note 2)
Note
The format of the Gregorian date should be yyyy-mm-dd (i.e a 3-dimensional array of ints)
The date is valid for all positive values.
Status: Canonical model
Version
2009 August 19
[iers2010], Explanatory Supplement American Ephemeris & Nautical Almanac (cf Comm CACM, 11, 657 (1968) and 15, 918 (1972)), p. 604
Definition at line 109 of file hardisp.hpp.
bool iers2010::hisp::leap (const int & iy)
This function determines whether a given integer year is a leap year.
Parameters
[in] iy Year (Note 1)
Returns
The function returns a boolean variable, denoting if the given year is leap (i.e if the returned value is 0, then the year is NOT leap).
Note
The year is a Gregorian year (integer).
Status: Canonical model.
Version
2009 August 19
Definition at line 54 of file utils.cpp.
int iers2010::hisp::mday (const int & iy, const int & m) inline
This function finds the day number of days before start of month m, of year iy, in Gregorian intercalation.
Parameters
[in] iy Given year
[in] m Given month
Returns
Day number of day before start of a month
Note
Status: Canonical model
Version
2009 July 29
Definition at line 84 of file hardisp.hpp.
References leap().
int iers2010::hisp::recurs (double * x, const int & n, const double * hc, const int & nf, const double * om, double * scr)
The purpose of the function is to perform sine and cosine recursion to fill in data x, of length n, for nf sines and cosines with frequencies om.
Parameters
[in] x Data provided from a file given as standard input from the MAIN program HARDISP.F (Note 1). This array will change!
[in] n Length of the data file x
[in] hc Array containing alternating cosine and sine coefficients
[in] nf Number of sine and cosine terms
[in] om Sine and cosine frequencies (Note 2)
[out] scr Scratch array of length 3 times nf which is returned as the recursion cr
Returns
Always returns 0
Note
See the MAIN program HARDISP header comments for detailed information.
The frequencies are normalized so that the Nyquist frequency is pi.
Status: Canonical model
Version
2009 August 19
Definition at line 26 of file recurs.cpp.
int iers2010::hisp::shells (double * x, int * k, const int & n)
This function sorts an array x, of length n, sorting upward, and returns an array k which may be used to key another array to the sorted pattern (i.e., if we had an array f to which x corresponded before sorting, then after calling SHELLS, f(k(1)) will be the element of f corresponding to the smallest x, f(k(2)) the next smallest, and so on).
Parameters
[in] x Array to be sorted (Note 1)
[in] n Length of input array x.
[out] k Sorted array that may be used to key another array.
Returns
Zero on sucess, 1 for failure.
Note
See the subroutine ADMINT header comments for detailed information.
The original fortran routine used a shell sorting algorithm (hence the name). This function does tha same as the original, but via a completely different way.
Status: Canonical model
Version
2009 August 19
Definition at line 26 of file shells.cpp.
int iers2010::hisp::spline (const int & nn, const double * x, const double * u, double * a, double * s)
The purpose of this function is to find an array s for the spline interpolator function EVAL.
Parameters
[in] nn Number of data points supplied, which may be negative (Note 1)
[in] x Array containing x-coordinates where function is sampled (Note 2)
[in] u Array containing sample values that are to be interpolated
[in] a Working space array of dimension at least nn
[out] s Output array of 2nd derivative at sample points
Returns
Always zero
Note
If the user wishes to force the derivatives at the ends of the series to assume specified values, he or she should put du(1)/dx and du(n)/dx in the variables s1 and s2 and call the subroutine with nn = -(number of terms in the series). Normally a parabola is fitted through the 1st and last 3 points to find the slopes. If less than 4 points are supplied, straight lines are fitted.
The sequence xx(1), xx(2), ... xx(nn) must be strictly increasing.
Status: Canonical model
Version
2009 August 26
Definition at line 36 of file spline.cpp.
References q().
int iers2010::hisp::tdfrph (const int * idood, const int * itm, double & freq, double & phase)
This subroutine returns the frequency and phase of a tidal constituent when its Doodson number is given as input.
Parameters
[in] idood Doodson number of a tidal constituent
[in] itm Date as integer array in UTC. The format should be: [year,day_of_year,hours,minutes,seconds].
[out] freq Frequency of a tidal constituent
[out] phase Phase of a tidal constituent (Note 1)
Note
The phases must be decreased by 90 degrees if the sum of the order and the species number is odd (as for the 2nd degree diurnals, and 3rd degree low frequency and semidiurnals). These phases may need further adjustment to allow for the spherical harmonic normalization used; e.g. for that used for the potential by Cartwright and Tayler, 180 degrees must be added for (species, order) = (1,2), (1,3), or (3,3).
Status: Class 1 model
Todo:
Generate a version of this function to use Julian Dates. Date manipulation/ transformation should not be used inside a sub-function.
*   Test case:
*     given input: For June 25, 2009 0 Hr 0 Min, M2 tide
*                  DATA IDOOD = / 2, 0, 0, 0, 0, 0 /
*
*     expected output: FREQ = 1.93227361605688D0
*                      PHASE = 303.362015399442D0
*
[iers2010]
Version
2013 September 11
Definition at line 40 of file tdfrph.cpp.
References etutc(), juldat(), leap(), and toymd().
int iers2010::hisp::toymd (const int * it1, int * it2)
This function converts times expressed in year and day of year to year-month-day.
Parameters
[in] it1 Time given in year and day of year (Note 1)
[out] it2 Time given in year-month-day format (Note 2)
Returns
Zero
Note
The time is split into a year, and the day of the year, i.e. it1 is an array of the form [year, day_of_year].
Time is represented as an array of the form [year, month, day]
Status: Class 1 model
[GPS] Toolbox:Date/Time conversion algorithms by Benjamin W. Remondi
Definition at line 20 of file utils.cpp.
References leap().