iers-2010: iers2010 Namespace Reference
iers2010 Namespace Reference
Namespaces
dtel
hisp
Functions
int pmsdnut2 (const double &, double *)
Function to compute the diurnal lunisolar effect on polar motion.
int utlibr (const double &, double &, double &)
Function to compute the subdiurnal librations in UT1.
int fundarg (const double &, double &, double &, double &, double &, double &)
Function to compute the lunisolar fundamental arguments from the model by Simon et al. (1994).
int fcnnut (const double &, double &, double &, double &, double &)
Computes corrections to the coordinates of the CIP to account for Free Core Nutation.
int arg2 (const int &, const double &, double *)
Computes the angular argument which depends on time for 11 tidal argument calculations.
int dehanttideinel (const double *, const double *, const double *, const double &, const double &, double *)
Computes tidal corrections of station displacements caused by lunar and solar gravitational attraction.
int dehanttideinel (const double *, const double *, const double *, const int &, const int &, const int &, const double &, double *)
int rg_zont2 (const double &, double &, double &, double &)
Computes the effects of zonal Earth tides on the rotation of the Earth.
Function Documentation
int iers2010::arg2 (const int & iyear, const double & day, double * angle)
Computes the angular argument which depends on time for 11 tidal argument calculations.
The purpose of the function is to compute the angular astronomical argument, which depends on time, for 11 tidal argument calculations. The order of the 11 angular quantities in vector angle are given below: 01-M2, 02-S2, 03-N2, 04-K2, 05-K1, 06-O1, 07-P1, 08-Q1, 09-Mf, 10-Mm, 11-Ssa (See Reference 1) This function is a translation/wrapper for the fortran ARG2 subroutine, found here : http://maia.usno.navy.mil/conv2010/software.html
Parameters
[in] iyear Four digit year (Note 1)
[in] day Day of Year Greenwich Time (Note 2)
[out] angle Angular argument for Schwiderski computation, in radians (Notes 3, 4 and 5)
Returns
An integer value which can be:
Returned Value Status
-1 Error; Invalid year
0 All ok; a new value has been computed
(Only when QUICK_EXIT enabled) 1 All ok; previous value for angle used.
Note
This subroutine is valid only after 1973 CE. A validation test has been added to stop the subroutine if an invalid year is used.
Example: 32.5 for February 1 12 Noon Example: 1.25 for January 1 6 AM
Ocean loading phases computed from Schwiderski's models refer to the phase of the associated solid Earth tide generating potential at the zero meridian according to
OL_DR = OL_AMP ' COS (SE_PHASE" - OL_PHASE)
where OL = OCEAN LOADING TIDE,
SE = SOLID EARTH TIDE GENERATING POTENTIAL.
If the harmonic tide development of Cartwright, et al. (CTE) (1971, 1973) is used, make sure that SE_PHASE" take into account:
the sign of SE_AMP in the tables of Cartwright et al.
that CTE'S SE_PHASE refers to a sine rather than a cosine function if (N+M) = (DEGREE + ORDER) of the tide spherical harmonic is odd. i.e. SE_PHASE" = TAU(T) ' N1 + S(T) ' N2 + H(T) ' N3
P(T) ' N4 + N'(T) ' N5 + PS(T) ' N6
PI If CTE'S amplitude coefficient < 0
PI/2 If (DEGREE + N1) is odd
where TAU ... PS = astronomical arguments,
N1 ... N6 = CTE'S argument numbers.
Most tide generating software compute SE_PHASE" (for use with cosines).
The double precision change from the original routine ARG.f to ARG2.F yields output differences on the order of 10^-9 radians.
The input array angle must be able to hold at least 11 doubles.
Status: Canonical model
Test case: given input: IYEAR = 2008 DAY = 311.5 (November 6 Noon) expected output: ANGLE(1) = 2.849663065753787805D0 rad ANGLE(2) = 6.28318080000000023D0 rad ANGLE(3) = 4.926040134021299366D0 rad ANGLE(4) = 1.608450491115348768D0 rad ANGLE(5) = 2.375021572352622456D0 rad ANGLE(6) = 0.4746414933980958040D0 rad ANGLE(7) = 3.908159227647345801D0 rad ANGLE(8) = 2.551018561669245344D0 rad ANGLE(9) = 5.041990012540757959D0 rad ANGLE(10) = 4.206816878908014701D0 rad ANGLE(11) = 1.608463638294885811D0 rad
Version
2011 October 07
[iers2010] Schwiderski, E., 1983, "Atlas of Ocean Tidal Charts and Maps, Part I: The Semidiurnal Principal Lunar Tide M2," Marine Geodesy, 6, pp. 219-256.
Definition at line 87 of file arg2.cpp.
int iers2010::dehanttideinel (const double * xsta, const double * xsun, const double * xmon, const double & jc1, const double & jc2, double * dxtide)
Computes tidal corrections of station displacements caused by lunar and solar gravitational attraction.
This function computes the station tidal displacement caused by lunar and solar gravitational attraction (see References). The computations are calculated by the following steps:
Step 1): General degree 2 and degree 3 corrections
CALL ST1IDIU + CALL ST1ISEM + CALL ST1L1.
Step 2): CALL STEP2DIU + CALL STEP2LON
It has been decided that the Step 3 non-correction for permanent tide would not be applied in order to avoid a jump in the reference frame. This Step 3 must be added in order to get the non-tidal station position and to conform with the IAG Resolution. This function is a translation/wrapper for the fortran DEHANTTIDEINEL subroutine, found here : http://maia.usno.navy.mil/conv2010/software.html
Parameters
[in] xsta Geocentric position of the IGS station (Note 1)
[in] xsun Geocentric position of the Sun (Note 2)
[in] xmon Geocentric position of the Moon (Note 2)
[in] jc1 Julian Centuries in TT (Note 6)
[in] jc2 Julian Centuries in TT (Note 6)
[out] dxtide Displacement vector (Note 5)
Note
The IGS station is in ITRF co-rotating frame. All coordinates, X, Y, and Z, are expressed in meters.
The position is in Earth Centered Earth Fixed (ECEF) frame. All coordinates are expressed in meters.
(OBSOLETE) The values are expressed in Coordinated Universal Time (UTC).
(OBSOLETE) The fractional hours in the day is computed as the hour + minutes/60.0
sec/3600.0.
The displacement vector is in the geocentric ITRF. All components are expressed in meters.
Parameters jc1 and jc2 constitute the date as Julian Centuries in TT time scale. The actual date is given by the addition jc1+jc2. Either jc1 or jc2 can be set to zero.
Status: Class 1
This fucnction is part of the package dehanttideinel, see ftp://maia.usno.navy.mil/conv2010/convupdt/chapter7/dehanttideinel/
Test case: given input: XSTA(1) = 4075578.385D0 meters XSTA(2) = 931852.890D0 meters XSTA(3) = 4801570.154D0 meters XSUN(1) = 137859926952.015D0 meters XSUN(2) = 54228127881.4350D0 meters XSUN(3) = 23509422341.6960D0 meters XMON(1) = -179996231.920342D0 meters XMON(2) = -312468450.131567D0 meters XMON(3) = -169288918.592160D0 meters YR = 2009 MONTH = 4 DAY = 13 FHR = 0.00D0 hour (T=0.092799473402287)
expected output: DXTIDE(1) = 0.7700420357108125891D-01 meters DXTIDE(2) = 0.6304056321824967613D-01 meters DXTIDE(3) = 0.5516568152597246810D-01 meters
Test case: given input: XSTA(1) = 1112189.660D0 meters XSTA(2) = -4842955.026D0 meters XSTA(3) = 3985352.284D0 meters XSUN(1) = -54537460436.2357D0 meters XSUN(2) = 130244288385.279D0 meters XSUN(3) = 56463429031.5996D0 meters XMON(1) = 300396716.912D0 meters XMON(2) = 243238281.451D0 meters XMON(3) = 120548075.939D0 meters YR = 2012 MONTH = 7 DAY = 13 FHR = 0.00D0 hour
expected output: DXTIDE(1) = -0.2036831479592075833D-01 meters DXTIDE(2) = 0.5658254776225972449D-01 meters DXTIDE(3) = -0.7597679676871742227D-01 meters
Version
2013 May 17
[iers2010],
Groten, E., 2000, Geodesists Handbook 2000, Part 4,
http://www.gfy.ku.dk/~iag/HB2000/part4/groten.htm. See also
''Parameters of Common Relevance of Astronomy, Geodesy, and
Geodynamics," J. Geod., 74, pp. 134-140
Mathews, P. M., Dehant, V., and Gipson, J. M., 1997, ''Tidal station
displacements," J. Geophys. Res., 102(B9), pp. 20,469-20,477
Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
IERS Technical Note No. 36, BKG (2010)
Pitjeva, E. and Standish, E. M., 2009, ''Proposals for the masses
of the three largest asteroids, the Moon-Earth mass ratio and the
Astronomical Unit," Celest. Mech. Dyn. Astr., 103, pp. 365-372
Ries, J. C., Eanes, R. J., Shum, C. K. and Watkins, M. M., 1992,
''Progress in the Determination of the Gravitational Coefficient
of the Earth," Geophys. Res. Lett., 19(6), pp. 529-531
CALL CAL2JD (YR, MONTH, DAY, JJM0, JJM1, STATUT) FHRD = FHR/24.D0
T=((JJM0-2451545.0D0)+JJM1+FHRD)/36525D0
CALL DAT (YR, MONTH, DAY, FHRD, DTT, STATUT)
DTT = DTT + 32.184D0
T=T+DTT/(3600.0D0*24.0D0*36525D0)
Definition at line 353 of file dehanttideinel.cpp.
References iers2010::dtel::_sprod_(), iers2010::dtel::st1idiu(), iers2010::dtel::st1isem(), iers2010::dtel::st1l1(), iers2010::dtel::step2diu(), and iers2010::dtel::step2lon().
int iers2010::dehanttideinel (const double * xsta, const double * xsun, const double * xmon, const int & yr, const int & month, const int & day, const double & fhr, double * dxtide)
This function computes the station tidal displacement caused by lunar and solar gravitational attraction (see References). The computations are calculated by the following steps:
Step 1): General degree 2 and degree 3 corrections
CALL ST1IDIU + CALL ST1ISEM + CALL ST1L1.
Step 2): CALL STEP2DIU + CALL STEP2LON
It has been decided that the Step 3 non-correction for permanent tide would not be applied in order to avoid a jump in the reference frame. This Step 3 must be added in order to get the non-tidal station position and to conform with the IAG Resolution. This function is a translation/wrapper for the fortran DEHANTTIDEINEL subroutine, found here : http://maia.usno.navy.mil/conv2010/software.html
Parameters
[in] xsta Geocentric position of the IGS station (Note 1)
[in] xsun Geocentric position of the Sun (Note 2)
[in] xmon Geocentric position of the Moon (Note 2)
[in] yr Year (Note 3)
[in] month Month (Note 3)
[in] day Day of Month (Note 3)
[in] fhr Hour in the day (Notes 3 and 4)
[out] dxtide Displacement vector (Note 5)
Note
The IGS station is in ITRF co-rotating frame. All coordinates, X, Y, and Z, are expressed in meters.
The position is in Earth Centered Earth Fixed (ECEF) frame. All coordinates are expressed in meters.
The values are expressed in Coordinated Universal Time (UTC).
The fractional hours in the day is computed as the hour + minutes/60.0
sec/3600.0.
The displacement vector is in the geocentric ITRF. All components are expressed in meters.
Parameters jc1 and jc2 constitute the date as Julian Centuries in TT time scale. The actual date is given by the addition jc1+jc2. Either jc1 or jc2 can be set to zero.
Status: Class 1
This fucnction is part of the package dehanttideinel, see ftp://maia.usno.navy.mil/conv2010/convupdt/chapter7/dehanttideinel/
Test case: given input: XSTA(1) = 4075578.385D0 meters XSTA(2) = 931852.890D0 meters XSTA(3) = 4801570.154D0 meters XSUN(1) = 137859926952.015D0 meters XSUN(2) = 54228127881.4350D0 meters XSUN(3) = 23509422341.6960D0 meters XMON(1) = -179996231.920342D0 meters XMON(2) = -312468450.131567D0 meters XMON(3) = -169288918.592160D0 meters YR = 2009 MONTH = 4 DAY = 13 FHR = 0.00D0 hour
expected output: DXTIDE(1) = 0.7700420357108125891D-01 meters DXTIDE(2) = 0.6304056321824967613D-01 meters DXTIDE(3) = 0.5516568152597246810D-01 meters
Test case: given input: XSTA(1) = 1112189.660D0 meters XSTA(2) = -4842955.026D0 meters XSTA(3) = 3985352.284D0 meters XSUN(1) = -54537460436.2357D0 meters XSUN(2) = 130244288385.279D0 meters XSUN(3) = 56463429031.5996D0 meters XMON(1) = 300396716.912D0 meters XMON(2) = 243238281.451D0 meters XMON(3) = 120548075.939D0 meters YR = 2012 MONTH = 7 DAY = 13 FHR = 0.00D0 hour
expected output: DXTIDE(1) = -0.2036831479592075833D-01 meters DXTIDE(2) = 0.5658254776225972449D-01 meters DXTIDE(3) = -0.7597679676871742227D-01 meters
Version
2013 May 17
[iers2010],
Groten, E., 2000, Geodesists Handbook 2000, Part 4,
http://www.gfy.ku.dk/~iag/HB2000/part4/groten.htm. See also
''Parameters of Common Relevance of Astronomy, Geodesy, and
Geodynamics," J. Geod., 74, pp. 134-140
Mathews, P. M., Dehant, V., and Gipson, J. M., 1997, ''Tidal station
displacements," J. Geophys. Res., 102(B9), pp. 20,469-20,477
Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
IERS Technical Note No. 36, BKG (2010)
Pitjeva, E. and Standish, E. M., 2009, ''Proposals for the masses
of the three largest asteroids, the Moon-Earth mass ratio and the
Astronomical Unit," Celest. Mech. Dyn. Astr., 103, pp. 365-372
Ries, J. C., Eanes, R. J., Shum, C. K. and Watkins, M. M., 1992,
''Progress in the Determination of the Gravitational Coefficient
of the Earth," Geophys. Res. Lett., 19(6), pp. 529-531
Definition at line 107 of file dehanttideinel.cpp.
References iers2010::dtel::_sprod_(), iers2010::dtel::cal2jd(), iers2010::dtel::dat(), iers2010::dtel::st1idiu(), iers2010::dtel::st1isem(), iers2010::dtel::st1l1(), iers2010::dtel::step2diu(), and iers2010::dtel::step2lon().
int iers2010::fcnnut (const double & mjd, double & x, double & y, double & dx, double & dy)
Computes corrections to the coordinates of the CIP to account for Free Core Nutation.
This subroutine computes the effects of the free core nutation. Please note that the table is updated each year (see Note 4). The parameter N needs to be incremented for each additional year in the table.
Parameters
[in] mjd Modified Julian Date, TDB (Note 1)
[out] x CIP offset x component, in microas (Note 2)
[out] y CIP offset y component, in microas (Note 2)
[out] dx Uncertainty of x component, in microas (Note 3)
[out] dy Uncertainty of y component, in microas (Note 3)
Returns
An integer value which can be either 0 (to denote that a new value has been computed) or 1 (to denote quick return). The returned integer has nothing to do with the status of the function and has no meaning if the QUICK_EXIT compilation flag was not used.
Warning
Contains data table to be updated each year, see http://syrte.obspm.fr/~lambert/fcn/
Note
Though the Modified Julian Date (MJD) is strictly TDB, it is usually more convenient to use TT, which makes no significant difference.
CIP is the Celestial Intermediate Pole. The expression used is given in microarcseconds.
The expression used is given in microarcseconds.
The updated table is maintained at the website http://syrte.obspm.fr/~lambert/fcn/.
Status: Class 3 model
Test case: (NOT UPDATED FOR 2013 TABLE, TO BE DONE) given input: MJD = 54790D0 Modified Julian Date, TDB
expected output: X = -176.8012290066270680D0 microarcseconds Y = -93.51855308903756736D0 microarcseconds dX = 3.745573770491803067D0 microarcseconds dY = 3.745573770491803067D0 microarcseconds
Version
2013 December 19
[iers2010]
1984.0
1985.0
1986.0
1987.0
1988.0
1989.0
1990.0
1991.0
1992.0
1993.0
1994.0
1995.0
1996.0
1997.0
1998.0
1999.0
2000.0
2001.0
2002.0
2003.0
2004.0
2005.0
2006.0
2007.0
2008.0
2009.0
2010.0
2011.0
2012.0
2013.0
microas
microas
Definition at line 51 of file fcnnut.cpp.
int iers2010::fundarg (const double & t, double & l, double & lp, double & f, double & d, double & om)
Function to compute the lunisolar fundamental arguments from the model by Simon et al. (1994).
This subroutine computes the lunisolar fundamental arguments. The model used is from Simon et al. (1994) as recommended by the IERS Conventions (2010). Refer to IERS Conventions (2010) Chapter 5 Sections 5.7.1 - 5.7.2 (pp. 57 - 59). This function is a translation/wrapper for the fortran FUNDARG subroutine, found here : http://maia.usno.navy.mil/conv2010/software.html
Parameters
[in] t TT, Julian centuries since J2000 (Note 1)
[out] l Mean anomaly of the Moon (Note 2)
[out] lp Mean anomaly of the Sun (Note 2)
[out] f L - OM (Notes 2 and 3)
[out] d Mean elongation of the Moon from the Sun (Note 2)
[out] om Mean longitude of the ascending node of the Moon (Note 2)
Returns
An integer value which can be either 0 (to denote that a new value for pm has been computed) or 1 (to denote quick return). The returned integer has nothing to do with the status of the function and has no meaning if the QUICK_EXIT compilation flag was not used.
Note
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference. Julian centuries since J2000 is (JD - 2451545.0)/36525.
The expression used is as adopted in IERS Conventions (2010) and is from Simon et al. (1994). Arguments are in radians.
L in this instance is the Mean Longitude of the Moon. OM is the Mean longitude of the ascending node of the Moon.
Status: Canonical model
Test case: given input: T = 0.07995893223819302 Julian centuries since J2000 (MJD = 54465) expected output: L = 2.291187512612069099 radians LP = 6.212931111003726414 radians F = 3.658025792050572989 radians D = 4.554139562402433228 radians OM = -0.5167379217231804489 radians
Version
2010 February 25
[iers2010], [simon94]
Definition at line 59 of file fundarg.cpp.
int iers2010::pmsdnut2 (const double & rmjd, double * pm)
Function to compute the diurnal lunisolar effect on polar motion.
This function evaluates the model of polar motion for a nonrigid Earth due to tidal gravitation. This polar motion is equivalent to the so-called "subdiurnal nutation." The model is a sum of a first order polynomial and 25 trigonometric terms (15 long periodic and 10 quasi diurnal) with coefficients given in Table 5.1a of the IERS Conventions (2010). This function is a translation/wrapper for the fortran PMSDNUT2 subroutine, found here : http://maia.usno.navy.mil/conv2010/software.html
Parameters
[in] rmjd Time expressed as modified Julian date
[out] pm Array of size 2, containing the polar motion coordinates (dx, dy) expressed in microarcseconds.
Returns
An integer value which can be either 0 (to denote that a new value for pm has been computed) or 1 (to denote quick return). The returned integer has nothing to do with the status of the function and has no meaning if the QUICK_EXIT compilation flag was not used.
Note
Status: Class 1 model
Warning
In the present version this subroutine neglects the linear trend and the long periodic terms of the expansion, for the reasons explained in Section 5.5.1.1 of the IERS Conventions (2010). If the full expansion is needed, set the parameter iband to 0 instead of 1, that is, replace the statement PARAMETER (iband = 1) to PARAMETER (iband = 0)
* Test case:
*     given input: rmjd = 54335D0 (August 23, 2007)
*
*     expected output: (dx) pm(1)  = 24.83144238273364834D0 microarcseconds
*                      (dy) pm(2) = -14.09240692041837661D0 microarcseconds
*
Version
2011 October 13
[iers2010]
Definition at line 50 of file pmsdnut2.cpp.
References fundarg().
int iers2010::rg_zont2 (const double & t, double & dut, double & dlod, double & domega)
Computes the effects of zonal Earth tides on the rotation of the Earth.
This function evaluates the effects of zonal Earth tides on the rotation of the Earth. The model used is a combination of Yoder et al. (1981) elastic body tide, Wahr and Bergen (1986) inelastic body tide, and Kantha et al. (1998) ocean tide models as recommended by the IERS Conventions (2010). Refer to Chapter 8 pp. 105 - 106. The latest version of the model is located at http://tai.bipm.org/iers/convupdt/convupdt_c8.html. This function is a translation/wrapper for the fortran RG_ZONT2 subroutine, found here : http://maia.usno.navy.mil/conv2010/software.html
Parameters
[in] t Julian centuries since J2000 (Note 1)
[out] dut Effect on UT1 (Note 2)
[out] dlod Effect on excess length of day (LOD) (Note 3)
[out] domega Effect on rotational speed (Note 4)
Returns
An integer value which can be either 0 (to denote that new values have been computed) or 1 (to denote quick return). The returned integer has nothing to do with the status of the function and has no meaning if the QUICK_EXIT compilation flag was not used.
Note
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference. Julian centuries since J2000 is (JD - 2451545.0)/36525.
The expression used is as adopted in IERS Conventions (2010). DUT is expressed in seconds and is double precision.
The expression used is as adopted in IERS Conventions (2010). DLOD is the excess in LOD and is expressed in seconds per day and is double precision. The phrase 'per day' is generally understood, so it has been omitted commonly in speech and literature. See: Stephenson, F. R., Morrison, L. V., Whitrow, G. J., 1984, "Long-Term Changes in the Rotation of the Earth: 700 B. C. to A. D. 1980 [and Discussion]", Phil. Trans. Roy. Soc. of London. Series A, 313, pp. 47 - 70.
The expression used is as adopted in IERS Conventions (2010). Rotational speed is expressed in radians per second and is double precision.
Status: Class 3 model
*   Test case:
*     given input: T = .07995893223819302 Julian centuries since J2000
*                  (MJD = 54465)
*     expected output: DUT    =  7.983287678576557467E-002 seconds
*                      DLOD   =  5.035331113978199288E-005 seconds / day
*                      DOMEGA = -4.249711616463017E-014 radians / second
*
Version
2011 December 20
[iers2010],
Yoder, C. F., Williams, J. G., and Parke, M. E., (1981), "Tidal Variations of Earth Rotation," J. Geophys. Res., 86, pp. 881 - 891.
Wahr, J. and Bergen, Z., (1986), "The effects of mantle anelasticity on nutations, Earth tides, and tidal variations in rotation rate," Geophys. J. Roy. astr. Soc., 87, pp. 633 - 668.
Kantha, L. H., Stewart, J. S., and Desai, S. D., (1998), "Long- period lunar fortnightly and monthly ocean tides," J. Geophys. Res., 103, pp. 12639 - 12647.
Gross, R. S., (2009), "Ocean tidal effects on Earth rotation," J. Geodyn., 48(3-5), pp. 219 - 225.
Petit, G. and Luzum, B. (eds.), IERS Conventions (2010), IERS Technical Note No. 36, BKG (2010)
Definition at line 80 of file rg_zont2.cpp.
References fundarg().
int iers2010::utlibr (const double & rmjd, double & dut1, double & dlod)
Function to compute the subdiurnal librations in UT1.
This function evaluates the model of subdiurnal libration in the axial component of rotation, expressed by UT1 and LOD. This effect is due to the influence of tidal gravitation on the departures of the Earth's mass distribution from the rotational symmetry, expressed by the non-zonal components of geopotential. The amplitudes have been computed for an elastic Earth with liquid core. The adopted truncation level is 0.033 microseconds in UT1 corresponding to the angular displacement of 0.5 microarcseconds or to 0.015 mm at the planet surface. With this truncation level the model contains 11 semidiurnal terms. The coefficients of the model are given in Table 5.1b of the IERS Conventions (2010). This function is a translation/wrapper for the fortran UTLIBR subroutine, found here : http://maia.usno.navy.mil/conv2010/software.html
Parameters
[in] rmjd Time expressed as modified Julian date
[out] dut1 Incremental UT1 in microseconds
[out] dlod Incremental LOD in microseconds per day
Returns
An integer value which can be either 0 (to denote that a new value for pm has been computed) or 1 (to denote quick return). The returned integer has nothing to do with the status of the function and has no meaning if the QUICK_EXIT compilation flag was not used.
Note
Status: Class 3 model
The procedure FUNDARG is the same as used by the program PMSDNUT2 which implements the corresponding model of the lunisolar libration in polar motion.
Test cases: given input: rmjd_a = 44239.1 (January 1, 1980 2:24.00) rmjd_b = 55227.4 (January 31, 2010 9:35.59)
expected output: dUT1_a = 2.441143834386761746D0 mus; dLOD_a = -14.78971247349449492D0 mus / day dUT1_b = - 2.655705844335680244D0 mus; dLOD_b = 27.39445826599846967D0 mus / day
Version
2010 June 23
[iers2010]
Definition at line 52 of file utlibr.cpp.
References fundarg().